[UartEndpoint fc]
Device = /dev/ttyAMA0
Baud = 115200

[UdpEndpoint companion]
Mode = normal
Address = 127.0.0.1
Port = 14551
RetryConnect = true

[UdpEndpoint navigation_service]
Mode = normal
Address = 127.0.0.1
Port = 14553

[UdpEndpoint telemetry_publisher]
Mode = normal
Address = 127.0.0.1
Port = 14562
