[UartEndpoint fc]
Device = /dev/ttyAMA0
Baud = 115200

[UdpEndpoint companion]
Mode = eav
Address = 127.0.0.1
Port = 14551

[UdpEndpoint navigation_service]
Mode = normal
Address = 127.0.0.1
Port = 14553

[UdpEndpoint telemetry_publisher]
Mode = normal
Address = 127.0.0.1
Port = 14562

[UdpEndpoint gcs_remote]
Mode = normal
Address = 0.0.0.0
Port = 14550
