REGISTRY_URL = "http://127.0.0.1:8080"
SIRENA_VERSION = "dev"
VIDEO_STATUS_UNIT = "video-streamer.service"
SOFTWARE_UPDATE_REBOOT_REQUIRED = 6
SOFTWARE_UPDATE_DISABLED = 7

STARLINK_IP = "192.168.100.1"
STARLINK_PORT = 9200
DEFAULT_TARGET = f"{STARLINK_IP}:{STARLINK_PORT}"
UART_GPS_PORT = "/dev/ttyAMA2"
UART_GPS_BAUD = 38400
UART_FC_PORT = "/dev/ttyAMA3"
UART_FC_BAUD = 38400

MANUAL_HOLD_SEC = 45.0
MANUAL_SATS = 12
MANUAL_ALT_MAX_DELTA_M = 120.0
STARLINK_FILTER_WINDOW = 15
STARLINK_POS_JUMP_MAX_M = 80.0
STARLINK_ALT_JUMP_MAX_M = 120.0
STARLINK_POLL_SEC = 1.0
STARLINK_RETRY_SEC = 5.0
STARLINK_ALGO = "NO_FILTER"
STARLINK_MAX_SPEED_MPS = 40.0
SOURCE_MODE = "AUTO"
NMEA_TALKER = "GP"
MAIN_LOOP_INTERVAL_SEC = 0.2
BROADCAST_NMEA = True
PRINT_EVERY = 5

# Backwards-compatible names for older modules. Prefer the typed names above.
DEFAULT_STARLINK_IP = STARLINK_IP
DEFAULT_STARLINK_PORT = STARLINK_PORT
